#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /login
    permanent: true